### ISSUE TITLE
Too many devices

### ISSUE THREAD

**Issue by leeandy1** [tomasbedrich/home-assistant-hikconnect#12]
Getting the following error in the integration:

Retrying setup: More than 100 devices is not supported yet. Please file an issue on GitHub.

Is there a way of limiting the Hik devices that are created in Home Assistant?

**Comment by tomasbedrich** [comment]
Thank you for reporting, I was never expecting to hit this limit, at least not soon. 😅

It is pretty straightforward fix, just to implement pagination.

Can you perhaps describe what is your use-case (how its possible that you have such a big amount of devices connected to your Hik-Connect account) and what kind of filtering/limiting would help you?

**Comment by leeandy1** [comment]
I have a total of 65 cameras over 9 separate NVR installs. 1 install is at my home and the other 8 are business locations spread across the UK. I am currently investigating access control to offer remote control of gates and entry points.

I suppose the easiest way of limiting for me would be to allow choosing which NVR's are brought into the integration.

**Comment by tomasbedrich** [comment]
There should be an ability to load more than 100 devices in version 1.0.0, please try.

You can limit which devices are shown in Home Assistant by disabling them via HA UI. Please try and let me know if it seems reasonable / too painful. I would rather avoid creating another limiting and filtering layer on top of HA, because it brings additional complexity and confusion.

**Comment by leeandy1** [comment]
This works fine for me in 1.0.0. Just 1 thing to note it has brought in 47 devices into HA which is less than the 65 I have in Hik Connect. I think it has missed 1 of my NVR's. I'll try and decipher what has not been brought in when I get a bit more time.

Thanks for the speedy fix and keep up the good work.

**Comment by tomasbedrich** [comment]
If you could follow [the guide](https://github.com/tomasbedrich/home-assistant-hikconnect/blob/main/DEBUGGING.md) and provide me some additional info, I can look at what can be wrong possibly.
