### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by bonepl** [tomasbedrich/home-assistant-hikconnect#14]
Hi, I'm inputing my hik-connect username and password but integration keeps rejecting me.

They work on hik-connect web as well as in iVMS-4200.

Any idea what can be wrong?

**Comment by tomasbedrich** [comment]
Hi, could you please provide the logs as per the guide? https://github.com/tomasbedrich/home-assistant-hikconnect/blob/main/DEBUGGING.md Then I can verify what's wrong.

**Comment by bonepl** [comment]
Nevermind, I upgraded firmware in my devices and it works fine now :)
