### ISSUE TITLE
Can't login when user is located in area non-matching his locale

### ISSUE THREAD

**Issue by jjmuriel** [tomasbedrich/home-assistant-hikconnect#16]
Hi, I'm typing my hik-connect username and password info but integration keeps rejecting me. The info works at hik-connect site.

Any idea what I doing wrong?

Version | core-2021.12.9
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.0-10-amd64
CPU Architecture | x86_64

`This error originated from a custom integration.

Logger: custom_components.hikconnect.config_flow
Source: custom_components/hikconnect/config_flow.py:26
Integration: Hik-Connect (documentation, issues)
First occurred: 10:47:17 (2 occurrences)
Last logged: 10:53:23

Hik-Connect login failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hikconnect/api.py", line 75, in login
    session_id = res_json["loginSession"]["sessionId"]
KeyError: 'loginSession'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/hikconnect/config_flow.py", line 39, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/hikconnect/config_flow.py", line 26, in validate_input
    await api.login(data["username"], data["password"])
  File "/usr/local/lib/python3.9/site-packages/hikconnect/api.py", line 77, in login
    raise LoginError("Unable to parse session_id from response.") from e
hikconnect.exceptions.LoginError: Unable to parse session_id from response.
`

`
2022-01-12 10:47:17 DEBUG (MainThread) [hikconnect.api] Got login response '{'meta': {'code': 1100, 'message': '客户端需要重定向用户请求域名(海外)', 'moreInfo': None}, 'loginArea': {'apiDomain': 'apiius.hik-connect.com', 'webDomain': 'ius.hik-connect.com', 'areaName': 'USA', 'areaId': 314}}'
2022-01-12 10:47:17 ERROR (MainThread) [custom_components.hikconnect.config_flow] Hik-Connect login failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/hikconnect/api.py", line 75, in login
    session_id = res_json["loginSession"]["sessionId"]
KeyError: 'loginSession'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/hikconnect/config_flow.py", line 39, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/hikconnect/config_flow.py", line 26, in validate_input
    await api.login(data["username"], data["password"])
  File "/usr/local/lib/python3.9/site-packages/hikconnect/api.py", line 77, in login
    raise LoginError("Unable to parse session_id from response.") from e
hikconnect.exceptions.LoginError: Unable to parse session_id from response.
`

**Comment by tomasbedrich** [comment]
Hi, can you please follow the debugging guide so that I know what is the issue?

https://github.com/tomasbedrich/home-assistant-hikconnect/blob/main/DEBUGGING.md

**Comment by jjmuriel** [comment]
Hi,
I followed this guide and sent you the logs to your email. Thanks.

**Comment by tomasbedrich** [comment]
It seems strange to me it tries to connect to US API, while you are probably located in Spain, right? Do you have any possible explanation, like VPN, DNS blocking, or..?

**Comment by tomasbedrich** [comment]
Moreover aren't there more logs to send? Maybe in this case it also helps if you send me your whole log file + config file, so that I can explain why it connects to US servers.

**Comment by jjmuriel** [comment]
I'm located in South America and the Hik-Connect App was configurated with USA account. I don't use VPN. I'll send you my whole log and config file, but I have some configurations splited in several YAML files. Maybe, I have to change the account to my country?

**Comment by jjmuriel** [comment]
If I change the account to my country, I can't add my Hikvision Doorbell. Instead, with the USA account it works.

**Comment by tomasbedrich** [comment]
Hm, could you please do `nslookup api.hik-connect.com` from your computer and send me the results?

**Comment by jjmuriel** [comment]
This is the output:
```
Server:		192.168.111.5
Address:	192.168.111.5#53

Non-authoritative answer:
api.hik-connect.com	canonical name = apiisa.hik-connect.com.
apiisa.hik-connect.com	canonical name = apisa-hik-connect-1930596709.sa-east-1.elb.amazonaws.com.
Name:	apisa-hik-connect-1930596709.sa-east-1.elb.amazonaws.com
Address: 54.233.110.148
Name:	apisa-hik-connect-1930596709.sa-east-1.elb.amazonaws.com
Address: 18.228.49.130
```

**Comment by tomasbedrich** [comment]
Ok, then it seems clear.

We have to redirect user to API domain returned in login request, if Hikconnect service provides such hint.

Thanks for your bug report and cooperation.

**Comment by tomasbedrich** [comment]
Please try version number 1.1.1 and let me know.

**Comment by jjmuriel** [comment]
Hi,
Now I can login, but now:
![image](https://user-images.githubusercontent.com/17131600/150133902-b11e12f6-8e89-4add-a4fa-a1fe97afbee5.png)


```
This error originated from a custom integration.

Logger: custom_components.hikconnect
Source: custom_components/hikconnect/__init__.py:30
Integration: Hik-Connect (documentation, issues)
First occurred: 07:49:14 (4 occurrences)
Last logged: 07:49:51

Unexpected error fetching hikconnect data: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/hikconnect/__init__.py", line 41, in async_update
    await relogin_if_needed()
  File "/config/custom_components/hikconnect/__init__.py", line 30, in relogin_if_needed
    needed = api.is_refresh_login_needed()
  File "/usr/local/lib/python3.9/site-packages/hikconnect/api.py", line 130, in is_refresh_login_needed
    return (self.login_valid_until - datetime.datetime.now()) < datetime.timedelta(
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'

```

**Comment by tomasbedrich** [comment]
Could you please provide logs again to my e-mail?

**Comment by jjmuriel** [comment]
Sure, I just sent you the logs.

**Comment by tomasbedrich** [comment]
Can you please try version 1.1.2?

**Comment by jjmuriel** [comment]
I did it, now there is not error, but I have 2 devices with the same name and no entities:
![image](https://user-images.githubusercontent.com/17131600/150204118-c9f5f05f-8c9d-4aa3-9216-8d4f7ff3634e.png)

Device no. 1
![image](https://user-images.githubusercontent.com/17131600/150204174-ce980af7-d821-4e07-93d1-ce8b53bafecc.png)

Device no. 2
![image](https://user-images.githubusercontent.com/17131600/150204263-14546753-4770-4fc1-b566-a0fcb823452f.png)


I have this video doorbell:
[https://us.hikvision.com/en/products/more-products/video-intercom/door-station/3-mp-outdoor-wi-fi-smart-doorbell-camera-ds-hd1](url)
I sent you the log file again. Thank you @tomasbedrich .

**Comment by tomasbedrich** [comment]
Okay, I'm glad that you are able to log in, so this bug is fixed.

The issue what you mention is #15. This is expected behavior, because currently the integrations supports **locks** only. Unfortunately, given your setup, the integration is not going to be useful for you (at least until something else than locks is implemented).

**Comment by jjmuriel** [comment]
I understand, thank you.
