### ISSUE TITLE
Capture incoming call and start two way audio

### ISSUE THREAD

**Issue by pergolafabio** [tomasbedrich/home-assistant-hikconnect#17]
@tomasbedrich

Do you think its possible to intercept the incoming call notification and start two way audio on the device? can you simulate it?

would be great if we could start the talk with HA

thnx

**Comment by tomasbedrich** [comment]
I guess this is one of the most advanced stuff. We can keep it here to track feature request, but first I would focus on "read-only" capture of video stream #6.

**Comment by pepsonEL** [comment]
First i think that better will be capture ring status....

**Comment by tomasbedrich** [comment]
I have it on my to-do list. I'm just to busy right now
