### ISSUE TITLE
Add Line Crossing and Motion Detection

### ISSUE THREAD

**Issue by peteshoard** [tomasbedrich/home-assistant-hikconnect#18]
I would like to be able to be able to use line crossings and motion detections to be able to automate certain things, like the turning on of outside lights or notifications that someone has entered my property.

Thanks

**Comment by pergolafabio** [comment]
Don't think that those events are on hikconnect, you need to use the SDK for that, I use it too

**Comment by pergolafabio** [comment]
Sure, i posted all isapi/sdk info here:

https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535

the script i used and modified was 👍 https://github.com/laszlojakab/hikvision-intercom-python-demo

addon i created is here, that one i use for events like door open/call status/ motion is also possible, just change sensor

https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535/726

the dockerfile, in that zip is old, change it to below, it includes now : lbffi-dev , for some reason some users need it for call status events

FROM python:3.7-slim

RUN pip install requests
RUN apt-get update && apt-get install -y libffi-dev

COPY hik.py /hik.py
COPY hcnetsdk.py /hcnetsdk.py
COPY lib /lib
COPY run.sh /run.sh 

CMD [ "/run.sh" ]
#CMD [ "python3", "hik.py" ]
#ENTRYPOINT ["tail", "-f", "/dev/null"]

**Comment by tomasbedrich** [comment]
Agree with @pergolafabio, these events are very probably not sent to Hik-Connect. If you show me such function in Hik-Connect application, I will be happy to re-open that.
