### ISSUE TITLE
Cannot open second door

### ISSUE THREAD

**Issue by pepsonEL** [tomasbedrich/home-assistant-hikconnect#2]
Hi i start test this integration. Now looks good i create script to open 1 door. When come back to come i test it. But good feature will be also add support to open second door and also automaticaly create view from Video Intercom Camera. This will be very good.

In app HikConnect i also has added my NVR with 7 cameras and now i see it in Home Assistant as entity lock.xxxxxxxx
Why and what it is ?

**Comment by tomasbedrich** [comment]
https://community.home-assistant.io/t/hik-connect/342202/3?u=tomasbedrich
