### ISSUE TITLE
API to send ISAPI commands

### ISSUE THREAD

**Issue by pergolafabio** [tomasbedrich/home-assistant-hikconnect#20]
Hey @tomasbedrich 

i have found the command to send ISAPI requests to the intercom, i think it can be verry usefull for you , that way you can get all ISAPI info from the outdoor station!, so you are not limited to info on hikconnect cloud...

2 examples

```
curl -X POST --header "sessionId: SESSIONID" --data "apiKey=100044&channelNo=1&deviceSerial=QXXXXXX&apiData=PUT /ISAPI/AccessControl/RemoteControl/door/1%0D%0A<RemoteControlDoor><cmd>open</cmd><channelNo>1</channelNo><controlType>monitor</controlType><password></password></RemoteControlDoor>" "https://apiieu.hik-connect.com/v3/userdevices/v1/isapi"


curl -X POST --header "sessionId: SESSIONID" --data "apiKey=100044&channelNo=1&deviceSerial=QXXXXX&apiData=GET /ISAPI/VideoIntercom/capabilities" "https://apiieu.hik-connect.com/v3/userdevices/v1/isapi"   
```

**Comment by pergolafabio** [comment]
These are also usefull maybe, to make extra services in HA? to cancell/answer/hangup a call 

`https://apiieu.hik-connect.com/v3/devconfig/v1/call/QXXX/operation?cmdId=3&handler=e6ldym`

use cmdId=3  or 2 or 5

**Comment by tomasbedrich** [comment]
Hey @pergolafabio, for the request above I'm getting this response:

```
{
    "meta": {
        "code": 2009,
        "message": "设备网络异常,请检查设备网络或者重试",
        "moreInfo": null
    }
}
```

I guess that's because my intercom doesn't support ISAPI at all.

It would be valuable to know how many people using this integration has devices supporting cloud-ISAPI. Currently, I don't have a clue.

**Comment by pergolafabio** [comment]
what intercom do you have?

**Comment by tomasbedrich** [comment]
https://github.com/tomasbedrich/home-assistant-hikconnect/blob/main/COMPATIBILITY.md?plain=1#L3

**Comment by tomasbedrich** [comment]
Thanks to your suggestions, I have been able to construct generic ISAPI proxy layer over Hik-Connect cloud. :) Great! I don't know where are you getting your tips from. :)

**Comment by tjunussov** [comment]
> nstruct generic ISAPI proxy layer

I have same error  "code": 2009, "message": "设备网络异常,请检查设备网络或者重试", 
however I could call http://{localip}/ISAPI/VideoIntercom/capabilities

what wrong i making ? i noticed what you use deviceSerial=QXXXXX where Q is prefix to SerialNumber ? i tried with Q and without nothing helped
