### ISSUE TITLE
Choose server hik-connect

### ISSUE THREAD

**Issue by psike01** [tomasbedrich/home-assistant-hikconnect#23]
Hello!
Is it possible to add choose server in your integration of the API?
When i register new user (in the hik-connect.com), and change country Russia my server change  from hik-connect.com to the hik-connectru.com.

And in the future all device transfer from "hik-connect.com" to the "hik-connectru.com". And i can't login to "hik-connect.com" (account not found), but ok login in "hik-connectru.com"

I think, it needs to change BASE_URL_API from api.hik-connect.com to api.hik-connectru.com

**Comment by tomasbedrich** [comment]
Hi, it makes sense to have it configurable. Sadly, it's not very high on my priority list now. Would you be able to contribute?

**Comment by ljshvdalvnel** [comment]
Need to change server, too..

**Comment by WiseProjects** [comment]
kinda useless without server changing option...

**Comment by OM-3kChcBjgFR2COfP** [comment]
Hi, i am from russia
so, need change server to https://i.hik-connectru.com/
is it possible? thanks!

**Comment by TolianIPB** [comment]
Hi, Me too. Need ti change server. Plz help.
