### ISSUE TITLE
is it possible to add a Russian server

### ISSUE THREAD

**Issue by xaos443** [tomasbedrich/home-assistant-hikconnect#24]
Hello. My devices are connected to my personal account https://i.hik-connectru.com . Add to your personal account https://www.hik-connect.com it doesn't work. is it possible to integrate with Russia?

**Comment by xaos443** [comment]
sorry. A week ago I wanted to ask a question, but they beat me to it. I wish I could do it myself(

**Comment by tomasbedrich** [comment]
Ok, closing in favor of #23.
