### ISSUE TITLE
Choose which devices are shown

### ISSUE THREAD

**Issue by fatmacheto** [tomasbedrich/home-assistant-hikconnect#25]
As of now the integration shows all devices added to HC including cameras, doorphones, alarms etc. Especially for the doorphones it adds the all the IP cameras added to the indoor stations which is not bad but it all add all empty entries. in other words if I have 3 added ip cameras into the indoor stations I get 16 added in total because that is the max added cameras per indoor station.

![image](https://user-images.githubusercontent.com/25221505/152828919-84a2540a-c824-4ee6-ac36-a016b9b43a9f.png)

**Comment by tomasbedrich** [comment]
Hi, let me follow up on this:

> if I have 3 added ip cameras into the indoor stations I get 16 added in total

Is there some way, how this is limited in Hik-Connect mobile app? If so, it would be nice to implement it here too.

**Comment by fatmacheto** [comment]
Yes, you can go to the indoor station and select which added cameras will be visible or not. As for the additional devices like cameras etc. you cannot choose to hide them, you need to remove them from your account.

**Comment by pergolafabio** [comment]
Are you talking about these? If yes, indeed , there is no way to delete them, I asked hikvision support before ..

![Screenshot_20220212-210307](https://user-images.githubusercontent.com/43251136/153726589-c41bdc76-054b-47e0-8861-270acf512c07.jpg)

**Comment by fatmacheto** [comment]
Actually by default  the app shows only the actual added IP cameras and when you go to settings you can hide them by pressing the eye icon.

Actually before you could see only intercom devices in that integration. After some update I started seeing all of my devices which makes no sense and only intercoms are supported.

![925D15F8-1DE4-4606-A19D-D3C0CAFA8C69](https://user-images.githubusercontent.com/25221505/153746064-af14a813-6006-496e-a9f2-0703c816964e.png)


![7426C538-A1FF-44F2-A797-D7B64263B1D6](https://user-images.githubusercontent.com/25221505/153746063-eff4d59a-e08c-4520-b29a-a103ec15b392.jpeg)

**Comment by tomasbedrich** [comment]
In version 2.2.0 hidden channels has been marked as disabled by default (using `entity_registry_enabled_default` - [docs](https://developers.home-assistant.io/docs/core/entity/).

**Comment by fatmacheto** [comment]
> In version 2.2.0 hidden channels has been marked as disabled by default (using `entity_registry_enabled_default` - [docs](https://developers.home-assistant.io/docs/core/entity/)).

Perfect!
