### ISSUE TITLE
Failing to login due to HV's app uses CAPCHA

### ISSUE THREAD

**Issue by Ben1709** [tomasbedrich/home-assistant-hikconnect#28]
Hi there,

first of all, thanks a ton for thie lovely integration. It worked fine (was able to see my door lock and cameras) until I changed my password several times within the HV app on my phone. Now the inegration in HA tells me this:
![HV hassio](https://user-images.githubusercontent.com/73833163/163205000-e90d9420-620c-446b-8006-ce1ccb29c527.png)

Funny thing, I still see my cameras and moving detections in my Dashboard. The only offline thing is my button for the door lock. Having checked the text file in case I missed something but no luck here. Any one also having trouble logging in? Re-installing your integration did not help. In fact it made my door lock button missing totally in my dashboard.

Thanks in advance

Cheers
Ben

**Comment by tomasbedrich** [comment]
Hi, please try logging in on the web page https://www.hik-connect.com/ or Hik-Connect mobile app. When this happened to me, it was sufficient to fill in captcha once there, and it worked again.

**Comment by Ben1709** [comment]
Hey.
That did the trick. Didn't even have to fill in Capcha on the website. 
In HA I just had to re-integrate your app and delete the old one. Great!
Thanks a ton👍👍👍
