### ISSUE TITLE
Add Hikvision logo

### ISSUE THREAD

**Issue by pepsonEL** [tomasbedrich/home-assistant-hikconnect#3]
Good feature (cosmetic) will be add logo HikVision to integration show in HACS and after install in Home Assistant. Now is blank.

**Comment by tomasbedrich** [comment]
Good idea. In progress: https://github.com/home-assistant/brands/pull/2847

**Comment by tomasbedrich** [comment]
I can see the logo now - closing. Please comment if it is not working for you.

**Comment by pepsonEL** [comment]
I still no see logo. Maybe new version should be release.

**Comment by tomasbedrich** [comment]
Try refresh without cache in your browser. CMD/CTRL + Shift + R.

**Comment by pepsonEL** [comment]
Still no see, i also cleat cache by F12 in chrome and nothing.... But probably to see logo i must install new integration which has logo ?

**Comment by tomasbedrich** [comment]
Strange.. It shouldn't require a new installation (this is how it worked on my side). It only requests the logo from here: https://brands.home-assistant.io/hikconnect/icon.png Maybe just give it some time.

**Comment by pepsonEL** [comment]
this link no workin
![nopage](https://user-images.githubusercontent.com/71824185/135410930-2831b7cf-7c68-4594-8e55-77b56e36dde5.jpg)
g

**Comment by tomasbedrich** [comment]
I trust you but it is working on my side. :) Just wait some time and it hopefully deletes itself from all the caches in between. :)

**Comment by pepsonEL** [comment]
I also try on other web browser and the same issue.

**Comment by pepsonEL** [comment]
Still no show logo. In my opinion something is wrong.

**Comment by pepsonEL** [comment]
In installed integration still no see logo look:
![logo](https://user-images.githubusercontent.com/71824185/135728559-02e2d0a4-fb8f-4617-aa1e-e8fce1624199.jpg)


But in list integration to install i see logo:
![list](https://user-images.githubusercontent.com/71824185/135728572-13469b16-c389-4fc9-ba6a-492022405012.jpg)

**Comment by pepsonEL** [comment]
please reopen it.

**Comment by tomasbedrich** [comment]
Hi @pepsonEL, I hear you with the logo issue. I still think we should wait (there is a max-age of 604800sec = 7d) / someone else should verify it.

Maybe if you can test it using `curl` from your PC? Can you please try following and put here the output?

```
curl --head https://brands.home-assistant.io/hikconnect/icon.png
curl --head https://brands.home-assistant.io/hikconnect/icon@2x.png
curl --head https://brands.home-assistant.io/hikconnect/logo.png
curl --head https://brands.home-assistant.io/hikconnect/logo@2x.png
```

**Comment by pepsonEL** [comment]
I dont have linux. I use Windows. But when i try open all this link:
https://brands.home-assistant.io/hikconnect/icon.png
https://brands.home-assistant.io/hikconnect/icon@2x.png
https://brands.home-assistant.io/hikconnect/logo.png
https://brands.home-assistant.io/hikconnect/logo@2x.png

all works and i see logos in this images.

**Comment by tomasbedrich** [comment]
There is some contradiction. [Previously you written](https://github.com/tomasbedrich/home-assistant-hikconnect/issues/3#issuecomment-930964407) that the link is not working (not even in another browser). [Today you wrote](https://github.com/tomasbedrich/home-assistant-hikconnect/issues/3#issuecomment-933225558) that all links are working. So is there some progress or not?

If yes, I think we should not continue with debugging, because it only takes time and we have a good chance that it fixes itself.

**Comment by pepsonEL** [comment]
Previously i test it in home. Yesterday i try this link in my work.
Logo is still unavailable. Please share screenshot where you show that you have logo in configuration>integration after install.

**Comment by pepsonEL** [comment]
Sorry now i test again and only one link no working correct:
[](https://brands.home-assistant.io/hikconnect/icon.png)
No show image and show this:
![135410930-2831b7cf-7c68-4594-8e55-77b56e36dde5](https://user-images.githubusercontent.com/71824185/135971205-4c27fc9d-8eb8-4608-a2ab-36782e6d0d90.jpg)

This links works ok and show image.
[](https://brands.home-assistant.io/hikconnect/icon@2x.png)
[](https://brands.home-assistant.io/hikconnect/logo.png)
[](https://brands.home-assistant.io/hikconnect/logo@2x.png)

**Comment by tomasbedrich** [comment]
![screenshot 2021-10-05 at 11 34 15](https://user-images.githubusercontent.com/4974343/135998265-4f8d9a47-2b0c-4dd3-9555-f4900bdcb753.jpg)

Here is the screenshot including sources panel, also here is the dump from Chrome network panel:

```
Request URL: https://brands.home-assistant.io/hikconnect/icon.png
Request Method: GET
Status Code: 200 
Remote Address: 172.67.68.90:443
Referrer Policy: no-referrer
accept-ranges: bytes
age: 474990
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
cache-control: public,max-age: 900,s-maxage=604800,must-revalidate
cf-bgj: imgq:100,h2pri
cf-cache-status: HIT
cf-polished: status=not_needed
cf-ray: 6995a8de3fac412c-PRG
content-length: 10728
content-type: image/png
date: Tue, 05 Oct 2021 09:35:23 GMT
etag: "540f1b86d0c0e914f64ee89c8b272b3a-ssl"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=XAtPAe9W3mtcNRQnUDpo%2FdHPZUwGKxxFSRPt4JQERUwwT6HrOdBqhe1KXVyPS9qiNMBvTwSYv9g3OZ2D0rCzcKexUHdJNxeQV0nNE5%2BbMQFPzkPC89szbcSLgxrCy0CcBz4fVcaYUwwk%2FQ%3D%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
vary: Accept-Encoding
x-nf-request-id: 01FGSQXZBT10VCKWDWXSWHZGB7
```

As you can see, there is `cache-control: public,max-age: 900,s-maxage=604800,must-revalidate`, so I guess it may stick for 604800 seconds with [poisioned cache](https://en.wikipedia.org/wiki/Cache_poisoning) (by HTTP response 404 - non-existing image).

If you want me to debug from your point of view, please send me [HAR file generated](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting) by loading your `/config/integrations` page.

**Comment by pepsonEL** [comment]
This is my:
look visibility: Hidde
![logos](https://user-images.githubusercontent.com/71824185/136002169-a983d9c0-459e-4987-b426-30a5733aba75.jpg)
n

**Comment by pepsonEL** [comment]
Ok now logo start visible . Now is OK. I dont do anything.

**Comment by tomasbedrich** [comment]
See it's probably 7 days from your first usage of the integration (according to the issue comment datetime). :)

**Comment by pepsonEL** [comment]
:)

**Comment by pepsonEL** [comment]
now good point will be issue #4 and #6
