### ISSUE TITLE
home-assistant-hikconnect is for home assistant supervisor?

### ISSUE THREAD

**Issue by javierferwolf** [tomasbedrich/home-assistant-hikconnect#30]
Hello everybody! this is a dumb question and sorry but this custom element is for home assistant supervisor?
since I can't get it to work!!

thank you

**Comment by tomasbedrich** [comment]
Nope, this works as Home Assistant integration. But given it is not included in core, you have to install it using some either HACS (as mentioned in README) or manually. Then, after it is installed, you can enable it as any other built-in integration
