### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Cornerstar31** [tomasbedrich/home-assistant-hikconnect#32]
tried to install, got this error

**Comment by tomasbedrich** [comment]
Hello, can you be more specific please? Please use this guide https://github.com/tomasbedrich/home-assistant-hikconnect/blob/main/DEBUGGING.md and provide complete log output afterwards.

**Comment by tomasbedrich** [comment]
Stale.
