### ISSUE TITLE
Hikvision Intercom Alarm Status

### ISSUE THREAD

**Issue by TheBartoMan** [tomasbedrich/home-assistant-hikconnect#33]
With the Hikvision Intercom, I can trigger bother Door1 and Door2 open, I can also see the status of the Intercom such as Idle or Call in progress.

This is all excellent thank you, but I cant see the status of the Alarm inputs to the intercom. These are what tell me it the door is currently open or closed.

Is it possible this can be added please?

**Comment by tomasbedrich** [comment]
Hello, if you follow the guide here: https://github.com/tomasbedrich/home-assistant-hikconnect/blob/main/DEBUGGING.md I can take a look if Alarm inputs are easily available to read.

**Comment by TokarevSergey** [comment]
Круто круто. Это важная функция. Скажите мне тоже нужно вам кинуть логи? Или у вас и так получается.
Cool cool.  This is an important feature.  Tell me, too, do you need to throw logs?  Or you can do it.

**Comment by tomasbedrich** [comment]
I can’t do anything without logs. Please send them to me.

**Comment by tomasbedrich** [comment]
Stale.
