### ISSUE TITLE
async_setup_platforms

### ISSUE THREAD

**Issue by DeimicUser** [tomasbedrich/home-assistant-hikconnect#34]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 12:01:44 (1 occurrences)
Last logged: 12:01:44

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for hikconnect using this method at custom_components/hikconnect/__init__.py, line 95: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by tomasbedrich** [comment]
Closed in 2.0.0.
