### ISSUE TITLE
kamery vidim ale nevidim jejich obraz

### ISSUE THREAD

**Issue by beatlesak** [tomasbedrich/home-assistant-hikconnect#35]
kamery vidim ale nevidim jejich obraz

**Comment by tomasbedrich** [comment]
Toto bohužel zatím není podporováno, viz: #6.

README.md:
> Features
Unlock a lock connected to Hikvision outdoor station.
Report call status of an indoor station (idle, ringing, call in progress) + call source (number of building, floor, etc.).
Nothing more yet, sorry. :) Visit an [issue tracker](https://github.com/tomasbedrich/home-assistant-hikconnect/issues) to discuss planned features.
