### ISSUE TITLE
Unlock a lock connected to Hikvision indoor station

### ISSUE THREAD

**Issue by dcec** [tomasbedrich/home-assistant-hikconnect#36]
Is possible to integrate com1 and com2 unlock on indoor station?

Now i have: 
1 indoor station DS-KH6320-WTE1
1 Door Station DS-KV8113-WME1(B)
1 Sub Door Station DS-KV8113-WME1(B)

i connect on hikconnect indoor station and the Door Station,
when register my account:
![image](https://user-images.githubusercontent.com/2527057/224565765-44470733-2570-42f3-a426-6b06b95477d7.png)
this is the entities:
![image](https://user-images.githubusercontent.com/2527057/224566005-a3ffe248-78b9-4265-985d-c396f36172e0.png)
on devices i find more strange items:
![image](https://user-images.githubusercontent.com/2527057/224566110-9fe3a09c-106a-405c-a0ad-f72ee54704b2.png)

**Comment by tomasbedrich** [comment]
I can see you have 6 lock entities in total. According to spec, DS-KH6320-WTE1 supports 2 relay outputs. Do I understand right, that you are missing the feature to control these relay outputs?

If this is true, please follow https://github.com/tomasbedrich/home-assistant-hikconnect/blob/main/DEBUGGING.md and I'll see if I can help.

![DS-KH6320-WTE1 spec](https://user-images.githubusercontent.com/4974343/226215376-973b1005-9156-4a2d-bab9-75554b55187d.jpg)

**Comment by dcec** [comment]
@tomasbedrich  sorry for delay,
i prepare a new home homeassistant instance for have clear log.

Now i have:
1 indoor station DS-KH6320-WTE1
1 Door Station DS-KV8113-WME1(B)
1 Sub Door Station DS-KV8113-WME1(B)

[home-assistant_2023-04-03T17-35-51.730Z.log](https://github.com/tomasbedrich/home-assistant-hikconnect/files/11140997/home-assistant_2023-04-03T17-35-51.730Z.log)

if you prefer i'm able to remove Sub Door Station for first testing

Thanks

**Comment by tomasbedrich** [comment]
Thanks for the logs.

> "Is possible to integrate com1 and com2 unlock on indoor station?"
You can unlock the them with https://www.home-assistant.io/integrations/lock/#service-lockunlock service, e.g. in your case use: `entity_id: lock.sub_door_station_1_lock`.

If this doesn't answer your question, can you please elaborate on what you are trying to achieve? Ideally please provide screenshot from Hikvision application.

**Comment by tomasbedrich** [comment]
Stale.
