### ISSUE TITLE
After updating to version 2.0.0 Hik-connect is missing

### ISSUE THREAD

**Issue by piwaneczko** [tomasbedrich/home-assistant-hikconnect#37]
Hi, after update to the 2.0 from 1.3 I don't see Hik-connect in the integrations list and my devices are disabled from front panel. I needed to reinstall 1.3 to have it worked. Home Assistant tot shows any log with errors.

**Comment by tomasbedrich** [comment]
Hello, what version of Home Assistant are you running?

**Comment by piwaneczko** [comment]
## System Health

version | core-2022.5.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | Europe/Warsaw

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4931
Installed Version | 1.24.5
Stage | running
Available Repositories | 1292
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 6
mode | storage

</details>

**Comment by tomasbedrich** [comment]
Thanks for the info. This is not a bug, it is expected according to the changelog: https://github.com/tomasbedrich/home-assistant-hikconnect/releases/tag/2.0.0 Please update your HA / stay on version 1.x.

**Comment by piwaneczko** [comment]
Thanks
