### ISSUE TITLE
Remove old devices

### ISSUE THREAD

**Issue by TheBartoMan** [tomasbedrich/home-assistant-hikconnect#38]
I used to have access to some camera systems that I now no longer have.

They don't show in my Hik-Connect apps, how do I remove them from Home Assistant?

Can you have it auto remove old devices?

**Comment by tomasbedrich** [comment]
Hello, I don't have experience with this on my own. But the integration should stop providing the device to Home Assistant as soon as it's not fetched from Hik-Connect. Afterwards, it depends on Home Assistant what happends with the leftover entities/devices. My guess is that they are marked as "unavailable" and you can delete them manually.

**Comment by tomasbedrich** [comment]
Stale.
