### ISSUE TITLE
Installed via HACS no way of configuring

### ISSUE THREAD

**Issue by tomm1ed** [tomasbedrich/home-assistant-hikconnect#55]
Installed version 2.4.0 on HA 2024.9.3 using HACS. After restart of HA no entry in Settings/Devices&Services so no way of setting up. No entries in logs, except:

`homeassistant    | 2024-10-02 15:57:39.532 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hikconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

Under Devices there is only this:
<img width="990" alt="hikconnect" src="https://github.com/user-attachments/assets/c4f5bbcc-a19b-4b00-83b1-8a1e82efd183">

**Comment by tomm1ed** [comment]
Tried 2.3.0 and even 1.3.0. None of them give me any way of configuring. What am I doing wrong?

**Comment by tomm1ed** [comment]
Running 
`docker exec homeassistant python -m homeassistant --script check_config --config /config --info hikconnect`
gives me the following output:
```
Testing configuration at /config
Successful config (partial)
  hikconnect:
```
Any insight how to continue?

**Comment by tomasbedrich** [comment]
Hello, the integration is configured using Config flow, i.e. using "Add Device" button from the UI.

YAML configuration is not supported.

**Comment by tomm1ed** [comment]
> Hello, the integration is configured using Config flow, i.e. using "Add Device" button from the UI.
> 
> YAML configuration is not supported.

Ha! That worked. My doorbell (DB-6003 clone from HiWatch) is added twice but it works at least now. Thanks!
