### ISSUE TITLE
Don't report camera-only devices as locks

### ISSUE THREAD

**Issue by tomasbedrich** [tomasbedrich/home-assistant-hikconnect#7]
(Splitting issue #2 on behalf of @pepsonEL)

> In app HikConnect i also has added my NVR with 7 cameras and now i see it in Home Assistant as entity lock.xxxxxxxx
Why and what it is ?

Quoting https://community.home-assistant.io/t/hik-connect/342202/5?u=tomasbedrich:

>  ... the integration is based on assumption, that _all devices_ connected to Hik-Connect has both lock + camera function available. This seems to be wrong assumption (based on your example) and we must fix it somehow.

**Comment by tomasbedrich** [comment]
Hi @pepsonEL, I created a new version f5ce468466e49c1dbdbef0c4ca045381797fb516. Despite I was focusing on fixing this  issue, I guess it may fix also #2. Can you please give it a try? Please, uninstall the old version first, then update using HACS, reinstall and restart Home Assistant. Then you can enable the integration again. Please send me your logs again to ja@tbedrich.cz if it doesn't work. Thanks.

**Comment by pepsonEL** [comment]
On this new version no found me any entieies after install new version. On email i send logs...

**Comment by tomasbedrich** [comment]
Thank you, it helped me to read your logs! There was a minor glitch that I expected all devices to report connected locks. It should be fixed in 1132902d969209f4fe2e7ee2cb5949e07faf51b4. Reinstall of integration is probably again needed.

**Comment by pepsonEL** [comment]
Ok i try. But please also see issue closed with problem logo....

**Comment by pepsonEL** [comment]
I test new version and now all works ok. Integration found me only 2device/2entity and it is 1 door and 2 door. And now when i create script open door works also for 1 and 2 door. Very good. Any cameras not found for me. I send you on email logs.

**Comment by tomasbedrich** [comment]
Good, I am closing this issue then + #2 too.

**Comment by pepsonEL** [comment]
Thanks good job. Now good will be add to also recognized camera from video intercom and status when idle when ring.
